### ISSUE TITLE
Unwanted changing of the total

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#117] opened 2018-04-17 16:35 UTC
What were you trying to do?
I am trying to pay and I am on the "checkout" Page and reloaded it accidentally

What was expected to happen?
I tryed to pay my order with clicking on "Confirm Order" and pay the outstanding invoice amount.

What was the actual result - what exactly did happen?
After reloading the total doubles.
- eventually important: It was an longer session.
=> So it could be an problem with caching the total payment

Which LiteCart version are you running?
Newest: litecart-2.1.1

**Comment by timint** [comment] 2018-05-23 21:40
Can this be reproduced?

**Comment by Fefke** [comment] 2018-05-24 07:59
The Problem was I tried to install my add-on (test)
and before it installed it was uninstalled (unexpected).
So I asked and the answer was: It uninstall before it install to delete given data.
⇒ So I am going to created an VQMOD to kick this function out

For you:
It’s not a bug but in my case an not needed function.


Regards

Felix
Von: T. Almroth
Gesendet: Mittwoch, 23. Mai 2018 23:40
An: litecart/litecart
Cc: Fefke; Author
Betreff: Re: [litecart/litecart] Unwanted changing of the total (#117)

Can this be reproduced?

**Comment by timint** [comment] 2018-05-28 20:41
Ok, closing this one if it's not a bug.
Can't you solve it my MySQL INSERT IGNORE som similar?

**Closed by timint** 2018-05-28 20:41 UTC
