### ISSUE TITLE
Admin "page refresh" v2a

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#33] opened 2017-03-17 12:31 UTC
When replacing the image in Admin->edit_category and edit_manufacturers, page does not "update", you must press "F5" to refresh.

**Comment by timint** [comment] 2017-03-17 13:21
This is because the browser have cached the image. Not a bug. Not sure if it's a great idea to build a workaround for browser cache. It caches content by design. Cache serves a purpose.

You can setup a development platform if you need to play around with content without interfering with production.

**Comment by gabbo2** [comment] 2017-03-17 14:45
No problem now that I know it works this way, I can set up a rule that not allows images to be cached in browser if it has "/admin" as a referer. :-)

**Comment by gabbo2** [comment] 2017-03-17 14:46
Oops.. i closed this by misstake :-)

**Comment by timint** [comment] 2017-03-18 16:14
No worries. :) I'm going to close this topic until further.

**Closed by timint** 2017-03-18 16:14 UTC
