### ISSUE TITLE
Payment module cant access updated order.

### ISSUE THREAD

**Issue by captainerd** [litecart/litecart#280] opened 2022-01-15 05:04 UTC
What were you trying to do?
..building payment module

What was expected to happen?
... get updated info from session::$data['order'] at the [ options function { ]

What was the actual result - what exactly did happen?
... Old data (due amount, etc) ignoring the changes (update pcs)

Which LiteCart version are you running?
.. 2.3.3

This will occur 
Case scenario #1. 

The payment module may need to inform the client of the due amount, 
(eg. Bank account wire, will need to include the total due price, again.. despite it is displayed in the bottom of the summary box.)

Case scenario #2 

Payment module asks for credit card information right on the page. it needs access to both $order->validate() in order to not accept payment if information.

-------------------

default template needs editing at pages/checkout.inc in the order the boxes are updated with the function queueUpdateTask(), summary must be updated first instead so shipping modules and payment have updated information.

Unless there is another way, then i would like to know.. thanks in advance.

**Comment by timint** [comment] 2022-01-15 15:36
I am closing this as not a bug. There is no order in the flow where options are generated. Just a subtotal. transfer() and after_process() however receives the order object. The order is created among with in the summary which is the last in the operational flow.

payment_transaction_id was deprecated in the early 1.x versions. Thanks for pointing this out.

**Closed by timint** 2022-01-15 15:36 UTC
