### ISSUE TITLE
smtp sending not working...

### ISSUE THREAD

**Issue by phrazer** [litecart/litecart#98] opened 2017-12-06 12:56 UTC
What were you trying to do?
sending email to customer after purchase

What was expected to happen?

What was the actual result - what exactly did happen?
problem is in smtp.php with AUTH not working...

Which LiteCart version are you running?
any 2.0 version...

**Comment by litecart** [comment] 2017-12-06 12:58
And you are sure that the smtp configuration is correct?

**Comment by phrazer** [comment] 2017-12-06 13:01
yes 100%. ill try with gmail also and report later...

**Comment by litecart** [comment] 2017-12-06 13:03
Screendump please, and you can censor sensitive parts of the values.

**Comment by phrazer** [comment] 2017-12-06 14:20
what should I screendump? I can show you errors.log if you like?

**Comment by phrazer** [comment] 2017-12-06 14:23
first there were this errors:
[06-Dec-2017 11:43:17 Europe] Warning: Failed sending email to krneki@foo.bar: No supported authentication methods (C) in ~/includes/classes/email.inc.php on line 153
 ← ~/includes/controllers/ctrl_order.inc.php on line 750 in send()
 ← ~/vqmod/vqcache/vq2-admin_orders.app_edit_order.inc.php on line 109 in email_order_copy()
 ← ~/admin/index.php on line 121 in include()
Request: POST /admin/?app=orders&doc=edit_order&order_id=1&redirect_url=%2Fadmin%2F%3Fapp%3Dorders%26doc%3Dorders HTTP/1.1

this was error here 
" if (preg_match('#250.AUTH ([^\r\n]+)#', $this->_last_response, $matches)) {" 
then I fixed this by adding... 
        if (preg_match('#250.AUTH (.*)#', $this->_last_response, $matches)) {
          $auths = explode(' ', trim($matches[1]));

and then this errors appear:
[06-Dec-2017 13:41:57 Europe] Warning: Failed sending email to krneki@foo.bar: Unexpected socket response; 535 Incorrect authentication data
 in ~/includes/classes/email.inc.php on line 153
 ← ~/includes/controllers/ctrl_order.inc.php on line 750 in send()
 ← ~/vqmod/vqcache/vq2-admin_orders.app_edit_order.inc.php on line 111 in email_order_copy()
 ← ~/admin/index.php on line 121 in include()
Request: POST /admin/?app=orders&doc=edit_order&order_id=1&redirect_url=%2Fadmin%2F%3Fapp%3Dorders%26doc%3Dorders HTTP/1.1

But I tryed same user/pass on another client and it works fine....

**Comment by litecart** [comment] 2017-12-06 16:16
A screendump of your smtp configuration.

Is it possible you delegate FTP access so this can be debugged?

**Comment by timint** [comment] 2017-12-11 19:41
![image](https://user-images.githubusercontent.com/359192/33850066-ef37afea-deb2-11e7-932f-ba876fb9060b.png)

SMTP with GMail works fine for me. I will be pushing some commits later this evening that enables a log file being created for your last SMTP session. You might wanna check it out.

Your error message says only a character "C"is all that was identified from the following:

```
        if (preg_match('#250.AUTH ([^\R]+)#', $this->_last_response, $matches)) {
          $auths = explode(' ', $matches[1]);
        }
```

Makes me wonder if your smtp server returned:
`250.AUTH C`

**Comment by timint** [comment] 2017-12-19 23:17
@phrazer any update on this case?

**Comment by litecart** [comment] 2018-03-06 02:25
Closing as not able to reproduce and no instructions how to simulate the issue.

**Closed by litecart** 2018-03-06 02:25 UTC
