### ISSUE TITLE
Predefined Attributes with Custom values only showing first item on front end

### ISSUE THREAD

**Issue by Darkrain82** [litecart/litecart#301] opened 2022-11-28 00:41 UTC
### What where you trying to do?
Since upgrade to 2.5.0 (may have been earlier but didn't notice until now a customer pointed out) have had products set up with a mixture of predefined values and custom values in attributes to choose colour etc. Predefined attributes are displaying fine (those with a [SELECT] * FROM `x_products_options_values` where value_id <> 0)

However those with a value_id of 0 (the custom values) are only showing one value on the front end.

### What actually happened?

![image](https://user-images.githubusercontent.com/85592828/204168683-d0ec254d-8b3c-492d-8675-6bc903b1af92.png)
Example attributes in back end

![image](https://user-images.githubusercontent.com/85592828/204168762-f4b9906a-f092-4740-985e-8ab6245158dc.png)
How the attributes display on the front end

![image](https://user-images.githubusercontent.com/85592828/204168952-06f4da5f-f922-4d99-ae81-50a54db399bd.png)
DB snapshot of values

### LiteCart Version

LiteCart 2.5.0

### PHP Version

PHP 7.3.33

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

Yes

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by timint** [comment] 2022-11-28 03:14
Thanks for reporting this issue. I believe this line is the cause of the issue:
https://github.com/litecart/litecart/blob/dev/public_html/includes/references/ref_product.inc.php#L341

Can you try replacing it with this instead:
`$option['values'][] = $value;`

**Comment by Darkrain82** [comment] 2022-11-28 08:27
> 

That appears to have done the trick, thank you for such a prompt response! It's much appreciated

**Comment by timint** [comment] 2022-11-28 15:56
Excellent, I will commit this as a fix. Released with the next minor release.

**Closed** 2022-11-29 00:08 UTC
Labels: bug
